name: Playwright Tests

on:
  workflow_dispatch: # Allows manual execution of the pipeline
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master] # Trigger when a pull request is opened/updated with the target branch as main or master

jobs:
  sauce-demo-e2e:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Display credentials for confirmation
      - name: Confirm credentials
        id: credentials
        run: |
          echo "PASSWORD is being used, length: ${{ secrets.PASSWORD }}"
          echo "Credentials are stored securely in GitHub secrets."

      # Step 2: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set environment variables
        run: |
          echo "URL=${{ secrets.URL }}" >> $GITHUB_ENV
          echo "USER_NAME=${{ secrets.USER_NAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          npm install
          # Install Playwright browser binaries
          npx playwright install chromium

      - name: Run Playwright E2E Tests
        run: npm run test:e2e

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
